export enum typeStructureEnum {
  associationCaritative = 'Association caritative',
  centreSocio = 'Centre socio-culturel',
  cyber = 'Cyberbase / Cybercentre',
  coworking = 'Espace de coworking',
  fablab = 'Fablab',
  grandOrganismePublic = 'Grand organisme public (CAF, CARSAT, Pôle emploi...)',
  mairie = 'Mairie',
  mdm = 'Maison de la Métropole (MDM)',
  mediatheque = 'Médiathèque / Bibliothèque',
  missionsLocales = 'Missions locales',
  mjc = 'MJC',
  pimms = 'Pimms',
  ressourcerie = 'Ressourcerie (matériel moindre coût / recyclé)',
  associationQuartier = 'Structure associative de quartier',
  formation = 'Structure de formation',
  insertion = "Structure d'insertion",
  sij = 'Structure information jeunesse (SIJ)',
}
