export enum PageTypeEnum {
  summary = 0,
  info = 1,
  accountInfo = 2,
  accountCredentials = 3,
  structureNameAndAddress = 4,
  structurePhone = 5,
  structureType = 6,
  structureAccessModality = 7,
  structureHours = 8,
  structurePmr = 9,
  structureWebAndSocialNetwork = 10,
  structurePublicTarget = 11,
  structureAccompaniment = 12,
  structureOtherAccompaniment = 13,
  structureWorkshop = 14,
  structureWorkshopPrice = 15,
  structureWifi = 16,
  structureEquipments = 17,
  structureLabels = 18,
  structureOtherServices = 29,
  structureDescription = 20,
  structureCovidInfo = 21,
  cgu = 22,
}
