export enum PageTypeEnum {
  summary = 0,
  info = 1,
  accountInfo = 2,
  accountCredentials = 3,
  structureNameAndAddress = 4,
  structurePhone = 5,
  structureType = 6,
  structureAccessModality = 7,
  structureHours = 8,
  structureHoursDetails = 9,
  structurePmr = 10,
  structureWebAndSocialNetwork = 11,
  structurePublicTarget = 12,
  structureAccompaniment = 13,
  structureOtherAccompaniment = 14,
  structureWorkshop = 15,
  structureWorkshopPrice = 16,
  structureWifi = 17,
  structureEquipments = 18,
  structureLabels = 19,
  structureOtherServices = 20,
  structureDescription = 21,
  structureCovidInfo = 22,
  cgu = 23,
}
